package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class SceneUtamaController {
	@FXML
	private TextField isian;

	// Event Listener on Button.onAction
	@FXML
	public void tmblLanjutDiklik(ActionEvent event) {
		// TODO Autogenerated
		Stage windowUtama = (Stage) isian.getScene().getWindow();
		String judul = isian.getText();
		windowUtama.setTitle(judul);
	}
}
